CREATE TABLE Members (
MemberID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE,
Phone VARCHAR(15),
Address VARCHAR(200))

CREATE TABLE Categories (
CategoryID INT AUTO_INCREMENT PRIMARY KEY,
CategoryName VARCHAR(100) NOT NULL,

CREATE TABLE Books (
BookID INT AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(200) NOT NULL,
Author VARCHAR(100),
CategoryID INT,
FOREIGN KEY (CategoryID) REFERENCES Categories (CategoryID));

CREATE TABLE Issued_Books (
IssueID INT AUTO_INCREMENT PRIMARY KEY,
BookID INT NOT NULL,
MemberID INT NOT NULL,
Issue Date DATE NOT NULL,
ReturnDate DATE,
Fine DECIMAL(8,2) DEFAULT 0,
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (MemberID) REFERENCES Members (MemberID));